// <auto-generated />

using System;
using AirJobs.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AirJobs.Data.Migrations
{
    [DbContext(typeof(AirJobsContext))]
    [Migration("20180909191128_CreatingSchedulingTable")]
    partial class CreatingSchedulingTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirJobs.Entities.Job.Job", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AddressId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Job");
                });

            modelBuilder.Entity("AirJobs.Entities.Job.Scheduling", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("JobDate");

                    b.Property<Guid>("JobId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Scheduling");
                });

            modelBuilder.Entity("AirJobs.Entities.Location.Address", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("CityId");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AirJobs.Entities.Location.City", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("StateId");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("AirJobs.Entities.Location.Country", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AirJobs.Entities.Location.State", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("AirJobs.Entities.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AddressId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("AirJobs.Entities.Job.Job", b =>
                {
                    b.HasOne("AirJobs.Entities.Location.Address", "Address")
                        .WithOne()
                        .HasForeignKey("AirJobs.Entities.Job.Job", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirJobs.Entities.Job.Scheduling", b =>
                {
                    b.HasOne("AirJobs.Entities.Job.Job", "Job")
                        .WithMany("Scheduling")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirJobs.Entities.User", "User")
                        .WithMany("Schedulings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AirJobs.Entities.Location.Address", b =>
                {
                    b.HasOne("AirJobs.Entities.Location.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("GeoCoordinatePortable.GeoCoordinate", "GeoLocation", b1 =>
                        {
                            b1.Property<Guid>("AddressId");

                            b1.Property<double>("Latitude")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnName("Longitude");

                            b1.ToTable("Address");

                            b1.HasOne("AirJobs.Entities.Location.Address")
                                .WithOne("GeoLocation")
                                .HasForeignKey("GeoCoordinatePortable.GeoCoordinate", "AddressId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("AirJobs.Entities.Location.City", b =>
                {
                    b.HasOne("AirJobs.Entities.Location.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirJobs.Entities.Location.State", b =>
                {
                    b.HasOne("AirJobs.Entities.Location.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirJobs.Entities.User", b =>
                {
                    b.HasOne("AirJobs.Entities.Location.Address", "Address")
                        .WithOne()
                        .HasForeignKey("AirJobs.Entities.User", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("AirJobs.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnName("FirstName")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnName("LastName")
                                .HasColumnType("varchar(200)");

                            b1.ToTable("User");

                            b1.HasOne("AirJobs.Entities.User")
                                .WithOne("Name")
                                .HasForeignKey("AirJobs.ValueObjects.Name", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
